version: "3.6"

services:
  web: 
    build: ./docker-web
    restart: always
    ports:
      - ${EXPOSE_APACHE_WEB_SERVER_ONLY_ON_IP_ADDRESS_COLON}${EXPOSE_APACHE_WEB_SERVER_ON_PORT}:80
    volumes:
      -   .:/var/www/html
    environment:
      MARIADB_USERNAME: ${MARIADB_USERNAME}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_HOSTNAME: ${MARIADB_HOSTNAME}
      MARIADB_PORT: ${MARIADB_PORT}
      MARIADB_DATABASE_NAME: ${MARIADB_DATABASE_NAME}

  mariadb:
    image: mariadb:10.4
    restart: always
    volumes: 
      -   ./data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - 127.0.0.1:${EXPOSE_MARIADB_ON_PORT}:${MARIADB_PORT}
